spring:
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate.default_batch_fetch_size: 1000
    hibernate:
      format_sql: true
      ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/video_conference?serverTimezone=Asia/Seoul&charaterEncoding=UTF-8
    username: user1
    password: vmfhwprxm

  domain:
    http://localhost:3000

janus:
  server: http://3.37.190.27:7088/admin
  admin:
    secret: janusoverlord